#Server
server:
  port: 8080

#Spring Configuration
spring:
  data:
    rest:
      base-path: '/api'
  datasource:
    url: 'jdbc:mysql://2.tcp.ngrok.io:14909/poly_techcam'
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: 'false'

  mail:
    host: smtp.gmail.com
    port: 587
    username: iamducthanh01@gmail.com
    password: adgjadgj
    properties:
      mail:
        smpt:
          auth: true
        smtp:
          starttls:
            enable: true
