#Server
server:
  port: 8080

#Spring Configuration
spring:
  data:
    rest:
      base-path: '/api'
  datasource:
    url: 'jdbc:mysql://localhost:3307/poly_techcam2'
    username: root
    password: Anhyeu12345@
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: 'false'

  mail:
    host: smtp.gmail.com
    port: 587
    username: techcam.poly@gmail.com
    password: motsaumot0mot@
    properties:
      mail:
        smpt:
          auth: true
        smtp:
          starttls:
            enable: true
techcam:
  schedule:
    birthday:
      cron: ${CU_SCHEDULE_BIRTHDAY_CRON:0 0 8 * * *}
      message: ${CU_MESSAGE_BRITHDAY:Hôm nay là sinh nhật của quý khách. TechCam xin chúc quý khách một ngày sinh nhật vui vẻ hạnh phúc!.<br>TechCam xin gửi tặng bạn voucher có mã là %s , hạn sử dụng  đến %s
       <br> Rất mong quý khách sẽ tiếp tục sử dụng dịch vụ của chúng tôi. <br> Lưu ý:khuyến mại sử dụng trên tổng hóa đơn thanh toán. Được phép sử dụng nhiều khuyến mại cùng một lúc}
      subject: ${CU_SUBJECT_BRITHDAY:Chúc Mừng Sinh Nhật Quý Khách}
      frommail: ${CU_FROM_MAIL_BRTHDAY:techcam.poly@gmail.com}